### ISSUE TITLE
edfapi dependency

### ISSUE THREAD

**Issue by mckenziephagen** [baharsener/visualEyes#50]
I've slacked about this a couple of times, but despite what I previously thought, the Eyelink Developers Kit _is_ required. There were some stray files that didn't get deleted when I thought I had uninstalled the Developers kit that lead to that misconception.

At this point, I've managed to install on the command line after manually downloading the `.dmg` file and converting that to a `.pkg` on macOS. I _should_ be able to download the `.dmg` file once I figure out the right `wget` syntax, which can then be put into our workflow yml file for testing. 

Since I've been fighting the the stupid environment for the yml file, I'm also considering just making a Docker for the CI testing, since I know a little bit more about debugging a Docker than I do debugging git workflows.

**Comment by BrendaQiu** [comment]
Is the link to downloading `.dmg` file publicly available? I'm asking because I remember having to register for the SR Research forum and wait for their confirmation before I can access any of those pages.

**Comment by BrendaQiu** [comment]
> Is the link to downloading `.dmg` file publicly available? I'm asking because I remember having to register for the SR Research forum and wait for their confirmation before I can access any of those pages.

This is also mentioned in [eyelinkio](https://github.com/BrendaQiu/eyelinkio#:~:text=You%20must%20register%20an%20account%20on%20the%20forum%20to%20access%20the%20download%20(registration%20is%20free)) and [eyelinkReader](https://github.com/alexander-pastukhov/eyelinkReader#:~:text=Note%20that%20you%20need%20to%20register%20and%20wait%20for%20your%20account%20to%20be%20activated.)

**Comment by mckenziephagen** [comment]
No, it's not. But there's a way to pass usernames and passwords to wget (and a way to keep those hidden in Github actions). 

So our users will still have to register and install, but for the purposes of CI testing, we can install it into the CI environment that way.

**Comment by mckenziephagen** [comment]
I actually wonder how that's handled in `eyelinkio` if there's any CI set up there, or if he just tests locally.

**Comment by mckenziephagen** [comment]
It looks like he just has linting setup for eyelinkio Github Actions. 

I'm more than happy to go down this rabbit hole since I need more familiarity with Github Actions for my own work.

**Comment by mckenziephagen** [comment]
Handled for CI purposes by copying download link - for now, general users can just manually download so we don't have to worry about license distribution rules.
